login: &login
  adapter: mysql2
  username: root
  password: risingsun
  encoding: utf8

development:
  <<: *login
  database: pr_d

test: &test
  <<: *login
  database: pr_t

production:
  <<: *login
  database: pr_p

cucumber:
  <<: *test
